version: '3.8'

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_INTERNAL_PORT}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  app:
    image: ${APP_IMAGE}
    container_name: ${APP_NAME}
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    volumes:
      #- ./docker/composer:/usr/local/bin/composer
      - /tmp/${APP_NAME}/logs:/tmp/logs:rw
      - ${APP_VOLUME}:/var/www/html:ro
      - ${APP_VOLUME}/../app:/var/www/app:ro
      - ${APP_VOLUME}/../vendor:/var/www/vendor:ro
      - ./INI/limits.ini:/usr/local/etc/php/conf.d/limits.ini:ro
      - ./INI/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:ro
      - ./INI/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped

  phpmyadmin:
    image: ${PMA_IMAGE}
    container_name: ${PMA_NAME}
    depends_on:
      - db
    volumes:
      - ./INI/limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./INI/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./INI/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  cache:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_NAME}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_INTERNAL_PORT}
    command: redis-server --save 20 1 --loglevel warning #--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ${REDIS_VOLUME}:/data
